### ISSUE TITLE
Badge: Add default badge for the User

### ISSUE THREAD

**Issue by LucasBrazi06** [Charge-Angels/ev-dashboard#1962] opened 2020-09-14 09:32 UTC

**Comment by jerome-benoit** [comment] 2020-11-29 10:14
+ Starting a remote transaction from a user with several tags and a default one is not choosing the default.

**Comment by jerome-benoit** [comment] 2020-12-16 14:40
@WillyLellouch: you confirm it works as intended?

**Comment by WillyLellouch** [comment] 2021-01-12 12:13
@jerome-benoit Tested with several chargers and several users with different types of badges.
The default badge is always selected.
However the default badge is selected even if deactivated, is this normal ?

**Comment by jerome-benoit** [comment] 2021-01-12 14:08
> @jerome-benoit Tested with several chargers and several users with different types of badges.
> The default badge is always selected.
> However the default badge is selected even if deactivated, is this normal ?

I don't think so. I think a warning should be display that the default badge is deactivated and the user should not be able to start a transaction.

**Comment by WillyLellouch** [comment] 2021-01-14 08:47
> I don't think so. I think a warning should be display that the default badge is deactivated and the user should not be able to start a transaction.

Is this going to constitute a new issue or should it be included in this one ?

**Comment by WillyLellouch** [comment] 2021-02-24 13:42
Ping for my earlier comment ?

**Comment by mahdibenromdhane** [comment] 2021-02-24 16:17
> > I don't think so. I think a warning should be display that the default badge is deactivated and the user should not be able to start a transaction.
> 
> Is this going to constitute a new issue or should it be included in this one ?

I have created a separated issue.

**Comment by WillyLellouch** [comment] 2021-02-25 07:01
Then this one is done. Thanks !
I'll go ahead and close this issue.

**Closed by WillyLellouch** 2021-02-25 07:01 UTC
Labels: feature, high-prio
